STATE_TEMPLATE = {
    "context": None,
    "submitted_authority_claim": None,
    "requested_jurisdiction": None,
    "submitted_ap_acf_class": None,
    "submitted_ap_acf_subclass": None,
    "submitted_policy_artifact": None,
    "resolved_authority": None,
    "jurisdiction": None,
    "action": None,
    "identity": None,
    "aj_saaf_operational_context": None,
    "abegf_request": None,

    # foundational baseline request evidence
    "digital_provenance_graph": None,
    "biometric_attestation_digest": None,
    "identity_jurisdictions": None,
    "identity_access_grants": None,
    "participant_id": None,
    "stakeholder_class": None,
    "participant_role": None,
    "participant_mandate_id": None,
    "impersonation_session_id": None,
    "impersonation_audience": None,
    "impersonation_challenge": None,
    "subject_id": None,
    "session_id": None,
    "service_id": None,
    "request_nonce": None,

    # foundational baseline control outputs
    "application_integrity_result": "",
    "application_integrity_result_digest": None,
    "application_integrity_receipt_digest": None,
    "application_integrity_manifest_digest": None,
    "application_integrity_runtime_measurement_digest": None,
    "application_integrity_trust_context_digest": None,

    "digital_provenance_result": "",
    "digital_provenance_reason": "",
    "digital_provenance_digest": None,
    "digital_provenance_lineage_authenticated": False,
    "digital_provenance_verification_trace": [],
    "digital_provenance_verification_receipt": {},
    "digital_provenance_lineage_only": True,

    "sovereign_identity_trace": [],
    "sovereign_identity_record": {},
    "sovereign_identity_digest": None,
    "sovereign_identity_result": "",
    "sovereign_identity_reason": "",
    "sovereign_identity_revocation_status": "",
    "sovereign_identity_revocation_sequence": None,

    "authority_boundary_trace": [],
    "authority_boundary_record": {},
    "authority_boundary_digest": None,
    "authority_boundary_trace_digest": None,
    "authority_boundary_result": "",
    "authority_boundary_reason": "",
    "stakeholder_label_grants_rights": False,
    "participant_authority_granted": False,
    "participant_licence_granted": False,
    "participant_execution_authority_granted": False,
    "participant_effect_authority_granted": False,
    "participant_pipeline_bypass_permitted": False,

    "impersonation_protection_trace": [],
    "impersonation_protection_record": {},
    "impersonation_protection_digest": None,
    "impersonation_protection_result": "",
    "impersonation_protection_reason": "",
    "impersonation_biometric_proof_established": False,
    "impersonation_identity_issued": False,
    "impersonation_identity_label_grants_access": False,
    "impersonation_role_label_grants_authority": False,
    "impersonation_mandate_label_grants_authority": False,
    "impersonation_access_granted": False,
    "impersonation_authority_granted": False,
    "impersonation_licence_granted": False,
    "impersonation_execution_authority_granted": False,
    "impersonation_effect_authority_granted": False,
    "impersonation_pipeline_bypass_permitted": False,

    "australian_minor_access": {},
    "australian_minor_access_hash_binding_index": None,
    "australian_minor_access_hash_binding_hash": None,

    "foundational_baseline_record": {},
    "foundational_baseline_result": "",
    "foundational_baseline_reason": "",
    "foundational_baseline_digest": None,
    "foundational_baseline_hash_binding_index": None,
    "foundational_baseline_hash_binding_hash": None,
    "foundational_baseline_authority_granted": False,
    "foundational_baseline_licence_granted": False,
    "foundational_baseline_execution_authority_granted": False,
    "foundational_baseline_effect_authority_granted": False,
    "foundational_baseline_pipeline_bypass_permitted": False,

    # P0 authority provenance: eligibility evidence only, never authority
    "authority_provenance_trace": [],
    "authority_provenance_record": {},
    "authority_provenance_digest": None,
    "authority_provenance_trace_digest": None,
    "authority_provenance_result": "",
    "authority_provenance_reason": "",
    "authority_provenance_trust_context_digest": None,
    "authority_provenance_clock_receipt_digest": None,
    "authority_provenance_registry_head_digest": None,
    "authority_provenance_authority_granted": False,
    "authority_provenance_licence_granted": False,
    "authority_provenance_execution_authority_granted": False,
    "authority_provenance_effect_authority_granted": False,
    "authority_provenance_pipeline_bypass_permitted": False,
    "authority_provenance_downstream_override_permitted": False,
    "governance_policy_record": {},
    "governance_policy_digest": None,

    # classification
    "ap_acf_class": None,
    "ap_acf_subclass": None,
    "requested_autonomy_level": None,
    "requested_system_mode": None,
    "autonomy_ceiling": None,
    "operational_environment": None,
    "public_exposure": None,
    "operational_scope": None,
    "environment_modifiers": None,
    "deployment_restrictions": None,
    "deployment_scope": None,

    "classification_result": None,
    "classification_reason": None,
    "classification_trace": [],

    # licensing
    "license_tier": None,
    "execution_rights": None,
    "license_profile": None,
    "licensing_result": None,
    "licensing_reason": None,
    "licensing_trace": [],
    "filed_licence_trace": [],
    "filed_licence_record": None,
    "filed_licence_result": None,
    "filed_licence_reason": None,
    "filed_licence_digest": None,
    "licence_id": None,
    "licence_invalidation_status": None,
    "licence_execution_disabled": False,
    "licence_invalidation_trace": [],
    "licence_invalidation_digest": None,
    "licence_revocation_status": None,
    "licence_revocation_sequence": None,

    # authenticated Sovereign Knowledge Graph authority substrate
    "skg_authority_trace": [],
    "skg_authority_record": None,
    "skg_authority_digest": None,
    "skg_authority_trace_digest": None,
    "skg_authority_result": None,
    "skg_authority_reason": None,
    "skg_authority_granted": False,
    "skg_execution_authority_granted": False,
    "skg_downstream_override_permitted": False,

    # governance
    "governance_result": None,
    "governance_reason": None,
    "governance_trace": [],

    # filed mandatory governance frameworks
    "filed_framework_trace": [],
    "filed_framework_results": {},
    "filed_framework_result": None,
    "filed_framework_reason": None,
    "filed_framework_digest": None,
    "gala_attestation": None,

    # filed lifecycle-governance components (implementation-defined V2)
    "filed_lifecycle_trace": [],
    "filed_lifecycle_results": {},
    "filed_lifecycle_record": None,
    "filed_lifecycle_result": None,
    "filed_lifecycle_reason": None,
    "filed_lifecycle_digest": None,

    # filed governance-integrity functions (implementation-defined V2)
    "filed_governance_integrity_revocation_binding": {},
    "filed_governance_integrity_trace": [],
    "filed_governance_integrity_results": {},
    "filed_governance_integrity_record": None,
    "filed_governance_integrity_result": None,
    "filed_governance_integrity_reason": None,
    "filed_governance_integrity_digest": None,
    "filed_governance_integrity_authority_granted": False,
    "filed_governance_integrity_licence_granted": False,
    "filed_governance_integrity_execution_authority_granted": False,
    "filed_governance_integrity_effect_granted": False,
    "filed_governance_integrity_bypass_permitted": False,

    # domains
    "domain_result": None,
    "domain_trace": [],

    # aurion
    "current_candidate": None,
    "candidate_attempt_count": 0,
    "aurion15_result": None,
    "aurion15_trace": [],

    # execution
    "decision": None,
    "effect_adapter_id": None,
    "effect_id": None,
    "effect_permit": None,
    "effect_receipt": None,
    "effect_result": None,
    "effect_trace": [],
}
